obj-$(CONFIG_MFD_CS35L41)		+= cs35l41-tables_test.o
obj-$(CONFIG_CS35L41_TABLES_TEST)		+= cs35l41-tables_test.o
obj-$(CONFIG_MFD_CS35L41)		+= cirrus-bd_test.o
obj-$(CONFIG_CIRRUS_BD_TEST)		+= cirrus-bd_test.o
obj-$(CONFIG_MFD_CS35L41)		+= cirrus-cal_test.o
obj-$(CONFIG_CIRRUS_CAL_TEST)		+= cirrus-cal_test.o
obj-$(CONFIG_MFD_CS35L41)		+= cirrus-pwr_test.o
obj-$(CONFIG_CIRRUS_PWR_TEST)		+= cirrus-pwr_test.o